{% set name = "pytibade" %}
{% set version = "1.0.0dev1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4cc2578830bbe0bb07d8eb7eefd51a22181a2dec2d84aea3774abe7263603ac7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - pytibade = pytibade.pytibade:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pycryptodome >=v3.8.2
  run:
    - python
    - pycryptodome >=v3.8.2

about:
  home: https://github.com/twlee79/py-tibade
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: Decrypt Titanium Backup for Android backups with Python/pycryptodome
  description: >
    This is a Python/pycryptodome-based implementation of a script to decrypt 
    backups made by Titanium Backup for Android.

extra:
  recipe-maintainers: twlee79
